---
functional:
  - Пользователь должен иметь возможность создать новую игру
  - Пользователь должен иметь возможность присоединиться к соданной игре 
  - Пользователь должен иметь возможность ыбрать язык программиоования в игре
  - Язык программирования не должен быть жёстко привязан к созданию сессии
  - Созданные игры должны отображаться в списке доступных для подключения
  - нужна система матчмейкинга (даже самая простая — очередь или список активных игр)
  - нужна синхронизация кода в реальном времени (видно, что печатает соперник)
  - Реализация двусторонней синхронизации кода (например, через Operational Transformation или CRDT)
  - Тесты запускаются только на локальном коде, не на коде соперника
non-functional:
  - Сайт нужно разработать с учетом удобства использования
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть удобным на мобильном устройстве
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Должна быть поддержка переподключения при разрыве соединения
  - Должна быть поддержка восстановления сессии по ID
  - Поддержка восстановления сессии по ID
  - Нужна система управления состоянием сессии
  - Игра удаляется из памяти только после выхода обоих
implicit:
  - Пользователь должен иметь возможность зарегистрироваться/авторизироваться
  - Не должно быть дубликатов пользователей